#%RAML 0.8
title: Please type API title here
version: v1
baseUri: http://localhost:8081/api
protocols: [ HTTP ]
/bu/all: 
  get: 
    responses: 
      200: 
        body: 
          text/plain: 
          application/json: 
/todb: 
  description: ""
  /businessunits: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /competencyareas: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /createrequest: 
    post: 
      body: 
        application/json: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /departments/{bu_id}: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /documenttypes: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /flagships: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /gwlibraries: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /osslicenses: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /osstype: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /publicationtype: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /registeredproxy: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /reporttypes: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /responsibilities: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /retentionperiod: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /ria: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
  /securityclass: 
    get: 
      responses: 
        200: 
          body: 
            text/plain: 
            application/json: 
